version: "3.9"
services:
api:
build: ./backend
env_file: .env
ports: ["8000:8000"]
depends_on: [redis]
volumes:
- ./backend:/app
web:
build: ./frontend
env_file: .env
ports: ["5173:5173"]
depends_on: [api]
volumes:
- ./frontend:/app
redis:
image: redis:7
ports: ["6379:6379"]
command: ["redis-server", "--appendonly", "yes"]